### ISSUE TITLE
Authentication error?

### ISSUE THREAD

**Issue by ghost** [kylewm/woodwind#42]
I have used WoodWind for a while. Recently I deleted my browser cache and cookies and wanted to use WoodWind again, but for some reason I cannot get authenticated. I'm not sure what is causing it. It was working fine, but I did update Known a few times with the most recent commit in Github.

Firstly after giving it my website (https://tinokremer.nl) it asks me to authenticate
![2016-02-02_160815](https://cloud.githubusercontent.com/assets/546983/12753434/610850b4-c9c7-11e5-930e-2e43d4ca18b7.png)

Then this happens:
![2016-02-02_160824](https://cloud.githubusercontent.com/assets/546983/12753452/73e6bf68-c9c7-11e5-9950-ee71d7177742.png)

In my logs I see no errors. I'm not sure if this is caused by me or WoodWind.

**Comment by karadaisy** [comment]
@kevinmarks was seeing this yesterday with *.withknown.com sites, but I thought it was fixed in git master :(

Could you do me a favor and check your `/IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php`. It should have`function post()` and _not_ `function postContent()` in it.

**Comment by ghost** [comment]
You nailed it @kylewm. As always you are correct and I'm messing things up. I did update Known, but never updated IdnoPlugins. I usually update them when needed. I never checked IndieAuth and now you mention it, I should have checked that first. Totally my bad, apologies.

I have updated IndiePub with the most recent commit and it's working perfectly fine now.

Thanks for your assistance @kylewm, hopefully @kevinmarks was able to fix his issue as well.

**Comment by kevinmarks** [comment]
I'm still getting auth errors on android chrome @benwerd did you deploy?

**Comment by benwerd** [comment]
@kevinmarks I had to withdraw the deployment due to an issue in the Twitter plugin (which revealed a long-standing feature inconsistency). Deploying right now.

**Comment by benwerd** [comment]
@kevinmarks Update to previous: we're having to hold back and fix. Changes to the way syndication accounts are stored have broken Convoy - working on it. Sorry.

**Comment by benwerd** [comment]
@kevinmarks It's been deployed now, and hosted sites are on the very latest code.

**Comment by kevinmarks** [comment]
Login now succeeds, but woodwind shows no subscriptions, possibly because
I'm now authenticated as http://known.kevinmarks.com/profile/kevinmarks

I suspect I was the plain domain before

**Comment by karadaisy** [comment]
Ah yeah same thing happened to me :( I can xfer your subscriptions to the new account, and will work on a real export/import process.
